import type { Settings } from "@/lib/types";

/** Used when the database isn't reachable yet, so the app can still render. */
export const DEFAULT_SETTINGS: Settings = {
  id: 1,
  name_en: "Amr",
  name_ar: "عمرو",
  role_en: "Full-Stack Web Developer",
  role_ar: "مطوّر ويب متكامل",
  tagline_en: "",
  tagline_ar: "",
  about_en: "",
  about_ar: "",
  email: "",
  phone: "",
  location_en: "Cairo, Egypt",
  location_ar: "القاهرة، مصر",
  github: "",
  linkedin: "",
  twitter: "",
  whatsapp: "",
  resume_url: "",
  accent: "#22d3ee",
  accent2: "#a855f7",
  available: true,
  years: 0,
  clients: 0,
  projects_done: 0,
  brand_mark: "</>",
  logo_url: "",
  avatar_url: "/avatar.png",
  hero_label_en: "Portfolio 2025",
  hero_label_ar: "أعمالي 2025",
  meta_title_en: "",
  meta_title_ar: "",
  meta_desc_en: "",
  meta_desc_ar: "",
  font_pair: "grotesk",
  show_globe: true,
  globe_title_en: "Working with clients worldwide",
  globe_title_ar: "بشتغل مع عملاء حول العالم",
  globe_desc_en: "",
  globe_desc_ar: "",
  globe_color: "#e9c98b",
};
